title: Bear Necessities
author: Kusine
email: kusine@bear-necessities.com
description: > # this means to ignore newlines until "baseurl:"
  A website for bears of all sizes.

# social links
twitter_username: your-twitter-handle
github_username:  Kusine

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
